# Generated by Django 4.2.7 on 2023-11-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_last_updated_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
