# Generated by Django 4.2.7 on 2024-01-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superpals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superpalworkoutrequest',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='superpalworkoutrequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='superpalworkoutrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Deleted', 'Deleted')], default='Pending', max_length=10),
        ),
    ]
