# Generated by Django 4.2.7 on 2024-01-01 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superpals', '0003_remove_superpalworkoutrequest_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpals',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
