# Generated by Django 4.2.7 on 2024-01-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superpals', '0004_alter_superpals_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superpalworkoutrequest',
            old_name='recipient_id',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='superpalworkoutrequest',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
