# Generated by Django 4.2.7 on 2024-01-01 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superpals', '0005_rename_recipient_id_superpalworkoutrequest_recipient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='superpalworkoutrequest',
            unique_together={('sender', 'recipient')},
        ),
    ]
