# Generated by Django 4.2.7 on 2024-01-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superpals', '0006_alter_superpalworkoutrequest_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='superpalworkoutrequest',
            unique_together=set(),
        ),
    ]
