# Generated by Django 4.2.7 on 2024-01-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superpals', '0007_alter_superpalworkoutrequest_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superpals',
            old_name='favorite_user',
            new_name='pal',
        ),
    ]
