# Generated by Django 4.2.7 on 2024-01-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('superpals', '0008_rename_favorite_user_superpals_pal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpals',
            name='pal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superpals_pal_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
