# Generated by Django 4.2.7 on 2024-01-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_user'),
        ('superpals', '0009_alter_superpals_pal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superpals_user', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='superpalworkoutrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_requests', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='superpalworkoutrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_requests', to='customers.customer'),
        ),
    ]
