# Generated by Django 4.2.7 on 2024-01-17 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20240117_0711'),
        ('superpals', '0010_alter_superpals_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpals',
            name='pal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superpals_pal_user', to='customers.customer'),
        ),
    ]
