# Generated by Django 4.2.7 on 2024-01-17 06:56
import datetime
import random

from django.db import migrations, transaction

from customers.models import Customer
from superpals.models import SuperPalWorkoutRequest, SuperPals


@transaction.atomic
def create_initial_data(apps, schema_editor):
    customers = Customer.objects.all()

    for _ in range(100):
        sender = random.choice(customers)
        recipient = random.choice(customers)

        while sender == recipient:
            recipient = random.choice(customers)

        SuperPals.objects.create(
            user=sender,
            pal=recipient,
        )

        random_workout_time = datetime.datetime.now() + datetime.timedelta(days=random.randint(1, 30))

        workout_request_data = {
            'sender': sender,
            'recipient': recipient,
            'workout_time': random_workout_time,
        }
        SuperPalWorkoutRequest.objects.create(**workout_request_data)


class Migration(migrations.Migration):
    dependencies = [
        ('superpals', '0011_alter_superpals_pal'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
