# Generated by Django 4.2.7 on 2024-01-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superpals', '0012_auto_20240117_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superpalworkoutrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Declined', 'Declined')], default='Pending', max_length=10),
        ),
    ]
