# Generated by Django 4.2.7 on 2023-12-04 03:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('trainings', '0002_training_name'),
        ('workouts', '0002_workout_rest_between_trainings_workout_trainings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('sex', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100),
                                                                django.core.validators.MinValueValidator(0)])),
                ('workout_streak', models.IntegerField(default=0)),
                ('workout_intensity',
                 models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')])),
                ('workout_difficulty', models.TextField(
                    choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Pro', 'Pro')])),
                ('rank', models.IntegerField(
                    choices=[('1', 'Warrior'), ('2', 'Guardian'), ('3', 'Defender'), ('4', 'Paladin'), ('5', 'Model'),
                             ('6', 'Exemplar'), ('7', 'Rescuer'), ('8', 'Champion')], default='1')),
                ('current_gym', models.CharField(max_length=40)),
                ('current_location', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_selected',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workout')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_image', models.CharField(max_length=255)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTrainingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training')),
            ],
        ),
    ]
