# Generated by Django 4.2.7 on 2024-01-17 06:11

from django.db import migrations, transaction
import json

from customers.models import Customer
from utils.enums import Rank
from authentication.models import User


@transaction.atomic
def create_initial_data(apps, schema_editor):
    with open('assets/dummy_data/customer.json', 'r') as file:
        data = json.load(file)
        temp_user = User.objects.create(
            username='darkmuha',
            email='darkmuha10@gmail.com',
            is_admin=True,
        )
        temp_user.set_password('Password123$')
        temp_user.is_superuser = True
        temp_user.is_staff = True
        temp_user.save()

        Customer.objects.create(
            user=temp_user,
            first_name="John",
            last_name="Doe",
            sex="Male",
            profile_picture="path/to/profile_picture.jpg",
            weight=70.5,
            height=280.0,
            age=25,
            workout_selected=None,
            workout_streak=0,
            workout_intensity="Low",
            workout_difficulty="Beginner",
            rank=1,
            current_gym="Gym Name",
            current_location="City, Country",
        )
        for customer_data in data:
            user = User.objects.create(
                username=customer_data['user']['username'],
                email=customer_data['user']['email'],
            )
            user.set_password(customer_data['user']['password'])
            user.save()

            Customer.objects.create(
                user=user,
                first_name=customer_data['first_name'],
                last_name=customer_data['last_name'],
                sex=customer_data['sex'],
                profile_picture=customer_data.get('profile_picture', None),
                weight=customer_data['weight'],
                height=customer_data['height'],
                age=customer_data['age'],
                workout_selected=None,
                workout_streak=customer_data.get('workout_streak', 0),
                workout_intensity=customer_data['workout_intensity'],
                workout_difficulty=customer_data['workout_difficulty'],
                rank=customer_data.get('rank', Rank.WARRIOR),
                current_gym=customer_data['current_gym'],
                current_location=customer_data['current_location'],
            )


class Migration(migrations.Migration):
    dependencies = [
        ('customers', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
