# Generated by Django 4.2.7 on 2024-01-22 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20240117_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rank',
            field=models.IntegerField(choices=[(1, 'Warrior'), (2, 'Guardian'), (3, 'Defender'), (4, 'Paladin'), (5, 'Model'), (6, 'Exemplar'), (7, 'Rescuer'), (8, 'Champion')], default=1),
        ),
        migrations.AlterField(
            model_name='progress',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
