# Generated by Django 4.2.7 on 2024-01-25 20:10

import customers.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_progress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(default=datetime.datetime.now, validators=[customers.models.validate_birthdate]),
        ),
    ]
