# Generated by Django 4.2.7 on 2024-01-25 20:10

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_customer_age_customer_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birthdate',
            field=models.DateField(validators=[customers.models.validate_birthdate]),
        ),
    ]
