# Generated by Django 4.2.7 on 2024-01-17 06:58
import random
import json

from django.db import migrations

from trainings.models import Training
from workouts.models import Workout


def create_initial_data(apps, schema_editor):
    with open('assets/dummy_data/workouts.json', 'r') as file:
        data = json.load(file)

        for workout_data in data:
            workout = Workout.objects.create(
                name=workout_data['name'],
                difficulty=workout_data['difficulty'],
                intensity=workout_data['intensity'],
                rest_between_trainings=workout_data['rest_between_trainings']
            )

            # Add random trainings to the workout
            all_trainings = list(Training.objects.all())
            random_trainings = random.sample(all_trainings, k=random.randint(1, 5))

            workout.trainings.set(random_trainings)


class Migration(migrations.Migration):
    dependencies = [
        ('workouts', '0002_workout_rest_between_trainings_workout_trainings_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_data)
    ]
